Be sure you've completed the steps on the [Initial Setup](setup.html) page before running this code.

For the setup, we're going to load a few libraries, load our specific Google Analytics credentials, and then authorize with Google.

```{r hidden-setup, echo=FALSE, message=FALSE, warning=FALSE}

# This snippet won't get rendered. It's purely for functionality that will make the web
# pages render more cleanly.

library(knitr)   # Mainly... so we can use kable()
```

```{r setup, message=FALSE, warning=FALSE}
# Load the necessary libraries. These libraries aren't all necessarily required for every
# example, but, for simplicity's sake, we're going ahead and including them in every example.
# The "typical" way to load these is simply with "library([package name])." But, the handy
# thing about using the approach below -- which uses the pacman package -- is that it will
# check that each package exists and actually install any that are missing before loading
# the package.
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse,         # Includes dplyr, ggplot2, and others; very key!
               devtools,          # Generally handy
               googleVis,         # Useful for some of the visualizations
               scales)            # Useful for some number formatting in the visualizations

# A function to check that a sufficiently current version of a specific package is 
# installed and loaded. This isn't particularly elegant, but it works.
package_check <- function(package, min_version, github_location){
  # Check if ANY version of the package is installed. This is clunky, but p_load_current_gh
  # wasn't playing nice (and this does need some conditional checking.)
  if(package %in% rownames(installed.packages())){
    # IF a version of the package is already installed, then check the *version* of that
    # package to make sure it's current enough. If it'snot, then re-install from GitHub
    if(packageVersion(package) < min_version) {
      devtools::install_github(github_location)
    }
  } else {
    devtools::install_github(github_location)
  }
  # Load the package
  library(package, character.only = TRUE)
}

# As needed, install and load googleAnalyticsR and ganalytics from GitHub
package_check("googleAnalyticsR", "0.5.0.9001", "MarkEdmondson1234/googleAnalyticsR")
package_check("ganalytics", "0.10.4.9000", "jdeboer/ganalytics")

# Authorize GA. Depending on if you've done this already and a .ga-httr-oauth file has
# been saved or not, this may pop you over to a browser to authenticate.
ga_auth(token = ".ga-httr-oauth")

# Set the view ID and the date range. If you want to, you can swap out the Sys.getenv()
# call and just replace that with a hardcoded value for the view ID. And, the start 
# and end date are currently set to choose the last 30 days, but those can be 
# hardcoded as well.
view_id <- Sys.getenv("GA_VIEW_ID")
start_date <- Sys.Date() - 31        # 30 days back from yesterday
end_date <- Sys.Date() - 1           # Yesterday

```

If that all runs with just some messages but no errors, then you're set for the next chunk of code: pulling the data.
